//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class native_wrap {
  public static double add(int a, double b) {
    double ret = native_wrapPINVOKE.add(a, b);
    return ret;
  }

  public static string string_side_effect {
    set {
      native_wrapPINVOKE.string_side_effect_set(value);
      if (native_wrapPINVOKE.SWIGPendingException.Pending) throw native_wrapPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = native_wrapPINVOKE.string_side_effect_get();
      if (native_wrapPINVOKE.SWIGPendingException.Pending) throw native_wrapPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public static double double_side_effect {
    set {
      native_wrapPINVOKE.double_side_effect_set(value);
    } 
    get {
      double ret = native_wrapPINVOKE.double_side_effect_get();
      return ret;
    } 
  }

  public static ReturnsVoid make_set_string_side_effect_callback() {
    ReturnsVoid ret = new ReturnsVoid(native_wrapPINVOKE.make_set_string_side_effect_callback(), true);
    return ret;
  }

  public static ReturnsSharedPtr test_shared_ptr() {
    ReturnsSharedPtr ret = new ReturnsSharedPtr(native_wrapPINVOKE.test_shared_ptr(), true);
    return ret;
  }

  public static ReturnsDouble make_add_set_double_side_effect_callback() {
    ReturnsDouble ret = new ReturnsDouble(native_wrapPINVOKE.make_add_set_double_side_effect_callback(), true);
    return ret;
  }

  public static double invoke_callback(ReturnsDouble in_) {
    double ret = native_wrapPINVOKE.invoke_callback(ReturnsDouble.getCPtr(ReturnsDouble.makeNative(in_)));
    if (native_wrapPINVOKE.SWIGPendingException.Pending) throw native_wrapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static readonly SWIGTYPE_p_f_int_double__double add_cb = new SWIGTYPE_p_f_int_double__double(native_wrapPINVOKE.add_cb_get(), false);
}
