//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Test : ITest {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal Test(global::System.IntPtr cPtr, bool cMemoryOwn) : base(native_wrapPINVOKE.Test_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Test obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          native_wrapPINVOKE.delete_Test(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public Test() : this(native_wrapPINVOKE.new_Test(), true) {
    SwigDirectorConnect();
  }

  public override void SetValue(int value) {
    if (SwigDerivedClassHasMethod("SetValue", swigMethodTypes0)) native_wrapPINVOKE.Test_SetValueSwigExplicitTest(swigCPtr, value); else native_wrapPINVOKE.Test_SetValue(swigCPtr, value);
    if (native_wrapPINVOKE.SWIGPendingException.Pending) throw native_wrapPINVOKE.SWIGPendingException.Retrieve();
  }

  public override int GetValue() {
    int ret = (SwigDerivedClassHasMethod("GetValue", swigMethodTypes1) ? native_wrapPINVOKE.Test_GetValueSwigExplicitTest(swigCPtr) : native_wrapPINVOKE.Test_GetValue(swigCPtr));
    if (native_wrapPINVOKE.SWIGPendingException.Pending) throw native_wrapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int Value {
    set {
      native_wrapPINVOKE.Test_Value_set(swigCPtr, value);
      if (native_wrapPINVOKE.SWIGPendingException.Pending) throw native_wrapPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      int ret = native_wrapPINVOKE.Test_Value_get(swigCPtr);
      if (native_wrapPINVOKE.SWIGPendingException.Pending) throw native_wrapPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("SetValue", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateTest_0(SwigDirectorMethodSetValue);
    if (SwigDerivedClassHasMethod("GetValue", swigMethodTypes1))
      swigDelegate1 = new SwigDelegateTest_1(SwigDirectorMethodGetValue);
    native_wrapPINVOKE.Test_director_connect(swigCPtr, swigDelegate0, swigDelegate1);
  }

  private bool SwigDerivedClassHasMethod(string methodName, global::System.Type[] methodTypes) {
    global::System.Reflection.MethodInfo methodInfo = this.GetType().GetMethod(methodName, global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance, null, methodTypes, null);
    bool hasDerivedMethod = methodInfo.DeclaringType.IsSubclassOf(typeof(Test));
    return hasDerivedMethod;
  }

  private void SwigDirectorMethodSetValue(int value) {
    SetValue(value);
  }

  private int SwigDirectorMethodGetValue() {
    return GetValue();
  }

  public delegate void SwigDelegateTest_0(int value);
  public delegate int SwigDelegateTest_1();

  private SwigDelegateTest_0 swigDelegate0;
  private SwigDelegateTest_1 swigDelegate1;

  private static global::System.Type[] swigMethodTypes0 = new global::System.Type[] { typeof(int) };
  private static global::System.Type[] swigMethodTypes1 = new global::System.Type[] {  };
}
