/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_native_wrap_WRAP_H_
#define SWIG_native_wrap_WRAP_H_

class SwigDirector_Test : public base::Test, public Swig::Director {

public:
    SwigDirector_Test();
    virtual void SetValue(int value);
    virtual int GetValue();
    virtual ~SwigDirector_Test();

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(int);
    typedef int (SWIGSTDCALL* SWIG_Callback1_t)();
    void swig_connect_director(SWIG_Callback0_t callbackSetValue, SWIG_Callback1_t callbackGetValue);

private:
    SWIG_Callback0_t swig_callbackSetValue;
    SWIG_Callback1_t swig_callbackGetValue;
    void swig_init_callbacks();
};

class SwigDirector_HasTest : public base::HasTest, public Swig::Director {

public:
    SwigDirector_HasTest(base::ITestPtr const &test);
    virtual void SetValue(int value);
    virtual int GetValue();
    virtual ~SwigDirector_HasTest();

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(int);
    typedef int (SWIGSTDCALL* SWIG_Callback1_t)();
    void swig_connect_director(SWIG_Callback0_t callbackSetValue, SWIG_Callback1_t callbackGetValue);

private:
    SWIG_Callback0_t swig_callbackSetValue;
    SWIG_Callback1_t swig_callbackGetValue;
    void swig_init_callbacks();
};

struct SwigDirector_ReturnsVoidDirector : public ReturnsVoidDirector, public Swig::Director {

public:
    SwigDirector_ReturnsVoidDirector();
    virtual ~SwigDirector_ReturnsVoidDirector();
    virtual void Invoke(std::string arg0);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(char *);
    void swig_connect_director(SWIG_Callback0_t callbackInvoke);

private:
    SWIG_Callback0_t swig_callbackInvoke;
    void swig_init_callbacks();
};

struct SwigDirector_ReturnsDoubleDirector : public ReturnsDoubleDirector, public Swig::Director {

public:
    SwigDirector_ReturnsDoubleDirector();
    virtual ~SwigDirector_ReturnsDoubleDirector();
    virtual double Invoke(int arg0, double arg1);

    typedef double (SWIGSTDCALL* SWIG_Callback0_t)(int, double);
    void swig_connect_director(SWIG_Callback0_t callbackInvoke);

private:
    SWIG_Callback0_t swig_callbackInvoke;
    void swig_init_callbacks();
};

struct SwigDirector_ReturnsSharedPtrDirector : public ReturnsSharedPtrDirector, public Swig::Director {

public:
    SwigDirector_ReturnsSharedPtrDirector();
    virtual ~SwigDirector_ReturnsSharedPtrDirector();
    virtual std::shared_ptr< Output > Invoke(Input const *arg0);

    typedef void * (SWIGSTDCALL* SWIG_Callback0_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackInvoke);

private:
    SWIG_Callback0_t swig_callbackInvoke;
    void swig_init_callbacks();
};


#endif
